spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.3.63:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      batch-size: 100
      properties:
        linger:
          ms: 10000
        compression:
          type: snappy
        enable:
          idempotence: true
      acks: "all"
    consumer:
      bootstrap-servers: 192.168.3.63:9092
      enable-auto-commit: false
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 100
      heartbeat-interval: 33
      properties:
        partition:
          assignment:
            strategy: org.apache.kafka.clients.consumer.StickyAssignor
      fetch-min-size: 1
  redis:
    host: 192.168.3.62
    database: 0
    password: 520612lgh

logging:
  level:
    org.springframework.kafka: DEBUG

